### PR TITLE
fix: increase performance

### LINKED ISSUE #55: Performance regression
On https://github.com/upbound/provider-aws we've seen a major performance degradation using `musttag` through golangci-lint lately (v1.52.2) , but that's also reproducible running it on its own (v0.7.0). See https://github.com/golangci/golangci-lint/issues/3910 for more details.

TL;DR: From the tracing syscall graph and some experiments run by @ldez it looks like the issue is with the number of `go list` calls done here: https://github.com/tmzane/musttag/blob/main/utils.go. Could be that our repository is kind of pathological, given that we are running it without issues on https://github.com/crossplane/crossplane, but still it's definitely some kind of regression, because it was running fine with older versions.

### PR DESCRIPTION
**Pull request by ldez**
Fixes #55

I was forced to rewrite the tests to be closer to a real context and be able to test my fix.

### CODE REVIEW

**Comment by phisco** [comment]
FYI: checked it out and can confirm it's solving our performance issues! 🙏 thanks @ldez!

**Comment by tmzane** [comment]
@ldez thank you for the PR (and the investigation)! I'm about to review it shortly.

File: builtins.go [hunk 1]
```diff
@@ -23,6 +23,10 @@ var builtins = []Func{
 	{Name: "gopkg.in/yaml.v3.Unmarshal", Tag: "yaml", ArgPos: 1},
 	{Name: "(*gopkg.in/yaml.v3.Encoder).Encode", Tag: "yaml", ArgPos: 0},
 	{Name: "(*gopkg.in/yaml.v3.Decoder).Decode", Tag: "yaml", ArgPos: 0},
+	{Name: "gopkg.in/yaml.v2.Marshal", Tag: "yaml", ArgPos: 0},
```
Comment (tmzane) [inline builtins.go:26]: Haven't seen `v2` being imported in a while, is it still in use? We should probably add these in a separate PR covered with tests :)

File: utils.go [hunk 2]
```diff
@@ -1,42 +1,34 @@
...
 )
 
-// mainModule returns the directory and the set of packages of the main module.
-func mainModule() (dir string, packages map[string]struct{}, _ error) {
-	// https://pkg.go.dev/cmd/go#hdr-Package_lists_and_patterns
-	// > When using modules, "all" expands to all packages in the main module
-	// > and their dependencies, including dependencies needed by tests of any of those.
+type modInfo struct {
+	Path      string `json:"Path"`
+	Dir       string `json:"Dir"`
```
Comment (tmzane) [inline utils.go:13]: We can now get the module's dir from here (previously, it was used at `musttag.go:167` to print relative paths)

File: builtins.go (hunk 1 above)
Comment (ldez) [reply builtins.go:26]: yes, I just added that because during my test the imports were wrong.

File: musttag.go [hunk 3]
```diff
@@ -202,13 +196,16 @@ func (c *checker) parseStructType(t types.Type, pos token.Pos) (*structType, boo
 		if pkg == nil {
 			return nil, false
 		}
-		if _, ok := c.mainModule[pkg.Path()]; !ok {
+
+		if !strings.HasPrefix(t.Obj().Pkg().Path(), c.mainModule) {
```
[the remark this answers is not in the document]
Comment (ldez) [reply musttag.go:200]: if someone has `example.com/a`/example.com/a/b` use-case we can think it's a monorepo so it's not a problem to report that.

File: musttag_test.go [hunk 4]
```diff
@@ -77,111 +77,19 @@ type nopT struct{}
...
-
-	for file, data := range stubs {
-		target := filepath.Join(testdata, "src", file)
-
-		err := os.MkdirAll(filepath.Dir(target), 0o777)
-		assert.NoErr[F](t, err)
-
-		err = os.WriteFile(target, []byte(data), 0o666)
-		assert.NoErr[F](t, err)
+	output, err := exec.Command("go", "mod", "vendor").CombinedOutput()
```
[the remark this answers is not in the document]
Comment (ldez) [reply musttag_test.go:90]: if a project uses a vendor you will need to strip `/vendor/`, it's not specific to these tests.

File: utils.go (hunk 2 above)
Comment (ldez) [reply utils.go:13]: you don't need to use relative path inside report (at least for golangci-lint)

File: musttag.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (tmzane) [reply musttag.go:200]: Agreed 👍

File: musttag_test.go (hunk 4 above)
[the remark this answers is not in the document]
Comment (tmzane) [reply musttag_test.go:90]: I'm not sure I follow, we don't ever want to report packages from `vendor`, do we? (since they are not a part of the main module)

[the remark this answers is not in the document]
Comment (ldez) [reply musttag_test.go:90]: there is confusion here: the strip is about the fact that a marshaling lib is in a vendor folder (ex `gopkg.in/yaml.v3`).

File: utils.go (hunk 2 above)
Comment (tmzane) [reply utils.go:13]: I was talking about reporting the position of the function call (`fnPos token.Position` in the `report` function), not the position of the struct type (which is trimmed by `golangci-lint` indeed). AFAIR, without using `filepath.Rel`, `fnPos` will be the full path

Comment (tmzane) [reply utils.go:13]: Coming back to our previous conversation, I think you were right about just reporting the function call instead of the struct type 😄 That would be much simpler

Comment (ldez) [reply utils.go:13]: yes, you have chosen the most "difficult" way :wink:

Just for context, our previous conversation was here: https://github.com/golangci/golangci-lint/pull/3624

Comment (tmzane) [reply utils.go:13]: I just tested it again, and it looks like `golangci-lint` prettifies all the paths in the report. Cool, you're right then!

Comment (tmzane) [reply utils.go:13]: I'm gonna implement a simpler version reporting just the function call position in a separate PR later

**Review by tmzane — APPROVED** [review]
